### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by SarveshMD** [csev/cc4e#34]
### I have a few questions. 
1) In book/code/c_026_01.c, a function is called get_line, but in the book, it is getline without the underscore in between. Should I change the name to getline or shall I leave it alone ?
2) In chap01.md, 1.5 A Collection of Useful Programs, we have four sub headers, File Copying, Character Counting, Line Counting and Word Counting. It would be helpful for readers if they were labelled as 1.5.1, 1.5.2 and so on. Shall I add those or shall we keep up with the book ?
3) It would be really helpful if we had a Table of Contents in the drop down which is in the top right corner of https://www.cc4e.com/book/. Even though that dropdown might seem like a table of contents, it does not show all the sub headings of each chapter. So we could add a new page in the dropdown called Table of Contents, and add all the chapters and sub headings of all chapters. If we decide that we can implement this, the problem is, we have seperate url for each chapter, for example https://www.cc4e.com/book/chap02.md , but we don't have url for each sub header, so we can't link the sub heading in the table of contents to go to the specific page and scroll to the correct sub heading, but we can make it go to the correct chapter. 
To solve this issue, we will have to write some php to add an id for each h2 tag in each chapter. For example, instead of this `<h2>1.1 Getting Started</h2>`, we will have to do `<h2 id="getting-started">1.1 Getting Started</h2>` or `<h2 id="1.1">1.1 Getting Started</h2>`, if we can change the html so that all h2's have an id, we can link the sub headings in Table of Contents to URLs like this https://cc4e.com/book/chap01.md#1.1 or https://cc4e.com/book/chap01.md#getting-started

![Screenshot from 2021-07-23 21-12-38](https://user-images.githubusercontent.com/76893756/126807483-ac1e07f2-cab3-4406-8709-59d42073e369.png)

4) In chap01.md, I found two random Yada lines, are they added for some reminder or shall I remove those ?
Yada:
![image](https://user-images.githubusercontent.com/76893756/126802736-caf9dac5-af11-4d42-8c94-c861255508d9.png)

**Comment by csev** [comment]
1.  I do not like deviating from the book - but since stdio.h already defines getline() I was forced to change it to get_line() or the examples have no chance of working.  Often the work in this book pre-dates stdio.h. 
2. Lets leave the headings alone for now.
3. YES!  :) Lets make a table of contents.  I just added `indx.md` and `toc.md` as starting points.  I always planned to add these - but they are in such bad shape and need so much manual work that I left them out - but if you want to work on them - feel free.  Lets keep them out of the drop downs until they are working a bit better.
4. HA HA :)  Yes - "Yada" is my stock "let me check for something" message - please remove them.  I left them in  by mistake.

**Comment by csev** [comment]
I missed the part about adding the h2's - yes - lets do it as you suggest (i.e. add the HTML bits)

**Comment by SarveshMD** [comment]
Thanks a lot @csev.

**Comment by SarveshMD** [comment]
Then, I think we should change the other references of the function from `getline` to `get_line`. There are some places in the book where`getline` is not changed to `get_line`.

**Comment by csev** [comment]
Yes - I have focused mostly on Chapter 1 - so there may be other references to getline that need changing - although we don't need to change it in code that uses stdio.h - because it will then just use the built in getline().

**Comment by csev** [comment]
Just make this a PR - I will merge it and the dig through it and fix it.

**Comment by csev** [comment]
I looked at your stuff - I *think* I can automatically generate the same HTML as github does in Parsedown.  Please PR this :)

**Comment by SarveshMD** [comment]
Done :)

**Comment by csev** [comment]
I just send in a commit to make this all work.

**Comment by SarveshMD** [comment]
Thanks Dr. Chuck.
