### ISSUE TITLE
c_167_01.c indention line 58-76

### ISSUE THREAD

**Issue by cahan0506** [csev/cc4e#42]
The FOR-statement is not a complete block.
- for (fp = _iob; fp < _iob + _NFILE; fp++)

Appendix A seems to be missing.

I read the book with great pleasure :-)

**Comment by csev** [comment]
This statement looks fine.   The "block" is the if statement on the following line.  The authors tend not to put curly braces in unless there is more than one statement in the block.  For those of us - modern style guide suggestions usually tell us to add the curly braces - any time a statement is on a new line - but this is not required in the language.

**Comment by cahan0506** [comment]
I found errata for 2. edition but I am sure that you already know about the page :-)
https://www.cs.princeton.edu/~bwk/cbook.html

**Comment by csev** [comment]
You are quite right - do you want me to fix it or do you want to send a pull request and get credit?

I just have not done Appendix A yet - I did not think it was significant.

**Comment by csev** [comment]
Closing via PR #44 - Thanks!
