### ISSUE TITLE
quiz in chapter 1 and 2

### ISSUE THREAD

**Issue by konkiourtidou** [csev/cc4e#46]
As you are in the process of creating and testing the "tools", perhaps the following will help you

chapter 1 quiz: 
In question 22 "Whay does the ..." -> What...

chapter 2 quiz: 
question 1: "int must ... iin length" -> ... in ...
question  8: "None of the above" answer doesn't always appear last, maybe it should be "None of the rest"
question  10: none of the given answers are correct for j, should 42 be 2?

Hope that helps you, 
Great work!!

**Comment by csev** [comment]
I just added you to the private cc4e repo so you can see the questions directly and instantly instead of seeing them a day or two later on the web site.

**Comment by csev** [comment]
For Chap2 / 10 - The question should be 'i' because the answer needs to be "42" :)

**Comment by csev** [comment]
I will let you do PR's in the private repo unless you want me to just fix them :)  Thanks!

**Comment by konkiourtidou** [comment]
I'll do it right now
Thanks!

Στις Παρ 29 Ιουλ 2022 στις 2:41 μ.μ., ο/η Charles Severance <
***@***.***> έγραψε:

**Comment by konkiourtidou** [comment]
If the answer needs to be 42 then the line "i += j++" should be "i += ++j"
isn't it?

Στις Παρ 29 Ιουλ 2022 στις 2:43 μ.μ., ο/η Konstantia Kiourtidou <
***@***.***> έγραψε:

**Comment by konkiourtidou** [comment]
fixed

**Comment by csev** [comment]
I just made the private repo public because it makes it easier to roll to production.   I will make it private again later as the course actually rolls out.

**Comment by csev** [comment]
Feel free to add more questions if you like :)  The more the merrier.
