### ISSUE TITLE
Darkmode on reading the textbook(the md file)

### ISSUE THREAD

**Issue by Gyangle** [csev/cc4e#51]
Hey Dr. Chuck,

I'm from your SI311. In my computer, I turn on the darkmode on everything due to my eyes' condition. However, it doesn't quite work when I'm reading the C Language textbook from my browser. I have tried using the "Read Mode" and different plug-ins, but it doesn't load the comment section of the book. I think this is because the source code indicates that you importing content from another md file.  

I have to manually change the html styles in my console, which works pretty well:
``` html
document.querySelector("body").style.color = "#ffffff" 
document.querySelector("body").style.backgroundColor = "#192734" 
```

Do you have any recommendation on enabling darkmode? Or this could be a potential feature to implement?

Before:
![image](https://user-images.githubusercontent.com/64182362/211909238-aa12af72-9aa7-47cf-9461-9bd4850cd08e.png)
After:
![Screenshot 2023-01-11 at 3 19 24 PM](https://user-images.githubusercontent.com/64182362/211909427-169042d7-ee2f-4a09-a277-c6417544d519.png)

**Comment by pravintargaryen** [comment]
You can enable this using CSS. I will edit the code and add the options for enabling both light and dark mode

**Comment by pravintargaryen** [comment]
The current Dark theme mode color is #000000. I will be changing this to #192734
