### ISSUE TITLE
Quiz typo, correct answer?

### ISSUE THREAD

**Issue by srcatto** [csev/cc4e#65]
Couldn't find the page/code for this.

https://www.cc4e.com/lessons/core
[Quiz: Types, Operators, and Expressions](https://www.cc4e.com/lessons_launch/cc4e_02_quiz)

(a) Q7 
If the result of the logical expression (12>10) is assignmed to an integer variable in C, what is the value that is assigned?

Typo - is **assignmed** 
Correct answer is expected to be 1 as, 12 > greater than 10, true (would be 0 if false.
Accepted as correct is 0, False.
K&R pg 189 appendix A 7.6 relational operators.

1 discussion report the question option is "\1". A browser render/typo in source issue?

(b) Q12
Since ANSI C does not have a predevined value for 'true', which of these is the most "correct" way to define a true value in ANSI C code?

typo - **predevined**
typo -  \#define TRUE (1)

Correct answer would be a non 0 value, that is 1 according to lessons. 
Marked as wrong, the TRUE (1).  The correct answer is TRUE (0==0) makes sense to me. I've seen this before. Using gcc -ansi to test. Both of those return 1 i.e. non 0 so either would be right.

**Comment by csev** [comment]
@srcatto I just fixed this in the repo and on the web site.  Nice to get this before the course moves onto Coursera.  I removed Q12 - I had other complaints on that question - so poof! it is gone :)  Thans.
