### ISSUE TITLE
Lesson 7 quiz - q2 wrong answer

### ISSUE THREAD

**Issue by deadloveskih** [csev/cc4e#80]
# Lesson 7 quiz - q2 wrong answer

https://www.cc4e.com/mod/gift/?quiz=chap05.txt

- **Lesson 7**
    - What is the C operator that takes an address of a value and retrieves the value pointed to by the address?

> [!WARNING]
> **The asterisk(*) is the correct answer, but is interpreted as incorrect.**

**Comment by csev** [comment]
Thanks!  I just fixed it.
