### ISSUE TITLE
Chapter 3 heading seems wrong

### ISSUE THREAD

**Issue by dante-haversham** [csev/cc4e#81]
Section 3.9 of the book is called _Goto's and Labels_, which seems to be grammatically incorrect. However, since the title of corresponding section in the original book is _Goto and Labels_, it should be corrected either way.

**Comment by csev** [comment]
Thanks.  You are both right and wrong.  In the 1984 edition section 3.9 is titled "Goto and Labels" but in the 1978 edition, it is "Goto's and Labels" - It took me a while to figure this on out. 

But nice catch :)

**Comment by dante-haversham** [comment]
Many thanks for finding that out. You never stop learning. 
:-)
