### ISSUE TITLE
Typo and difficult to read

### ISSUE THREAD

**Issue by mtotschnig** [csev/cc4e#94]
I stumbled upon the typo with the first then in this sentence

https://github.com/csev/cc4e/blob/39b7cdef9b3db9d3a673b345b7a4c9ff8acdb41e/book/notes/n_133_01.md?plain=1#L1

Not being a native English speaker I was not sure if it should be:

By now, you know when the authors mention the PDP-11

or 

By now, you know that when the authors mention the PDP-11

And  asked ChatGPT, which came up with some additional suggestions that make sense, IMHO:

> Yes, there are a few issues with the sentence you provided. Here's a revised version:
>"By now, you know that when the authors mention the PDP-11, they are discussing the challenge of making C work on previous generation computers with short memory words and small amounts of memory, while simultaneously ensuring its compatibility with the incoming generation of computers with larger words and more memory."
>This revision clarifies the relationship between the mention of the PDP-11 and the challenge of making C work on different generations of computers. It also improves the overall clarity and structure of the sentence.

**Comment by csev** [comment]
All fixed.  Thanks!
