### ISSUE TITLE
I tried to compile the code from minute 1:29:36 from youtube video of the course

### ISSUE THREAD

**Issue by avlcat** [csev/cc4e#97]
Using cc4e.com compiler it did work properly. Using clang or gcc13 did not worked. Maybe I did not knew how to switch to K&R code, I don't know?

The code that did not properly work for me (it gives buss error, core dumped when the input exceeds array size):

#include <stdio.h>

int main() {
	char name[11];
	printf("Enter your name:\n");
	scanf("%[^\n]10s", name);
	printf("Hello, %s\n", name);
}

The code that worked for me:

#include <stdio.h>

int main() {
	char name[11];
	printf("Enter your name:\n");
	scanf("%10[^\n]",name);
	printf("Hello, %s\n", name);
}

I use a smaller array to demonstrate the code, it's easier to test.

"To compile K&R C code with GCC, you can generally use the default settings of the compiler, as it is designed to support backward compatibility with K&R C code."

**Comment by csev** [comment]
I don't think this is a compiler switch issue - I just thing the second version is the correct version.   Do I have a reference in my code or slides or book that is incorrect?  I took a quick look and found no usage of scanf like this in my content.   But if there is let me know.

/Chuck

**Comment by csev** [comment]
Found it.   I changed the sample code and the PowerPoint.

**Comment by csev** [comment]
I uploaded the new video to youtube.  Thanks.

**Comment by avlcat** [comment]
wow that was fast, thank you ! (sorry I am a beginner, I did not knew if it's an issue with the code or I am doing something wrong)
