### ISSUE TITLE
I'm not sure if this is a mistake or something else.

### ISSUE THREAD

**Issue by GodRishUniverse** [csev/cc4e#99]
The course has been configured on Coursera but in the `TreeMaps` and `HashMaps` section on [www.cc4e.com](url) - the quiz says that it is yet to be configured. 

I was hoping maybe this is a mistake that needs to be rectified.

**Comment by csev** [comment]
This has been fixed - could you check and verify?  Thanks.

**Comment by GodRishUniverse** [comment]
Yes! Thank you!

**Comment by csev** [comment]
Thank you.
